### ISSUE TITLE
[config] version geodata on server

### ISSUE THREAD

**Issue by onlyjsmith** [locational/douma-api#26]
Relates to App https://github.com/locational/douma-app/issues/211
Relates to Validation https://github.com/locational/application-registry-validation/issues/15

-	[ ] Test geodata endpoints
-	[ ] Extend geodata endpoints to include versions
-	[ ] List Geodata versions for an instance
-	[ ] upload a geodata version to  instance/level/version
-	[ ] download a geodata version from instance/level/version
-	[ ] download a default geodata version from instance/level
-	[ ] bump geodata version by uploading to instace/level
-	[ ] Enforce geodata Validation
